### ISSUE TITLE
swift compatibility

### ISSUE THREAD

**Issue by galileomd** [50ButtonsEach/fliclib-ios#2]
hi, built a basic swift app with the latest library and getting these errors on compile... any ideas?
here's the sample code with demo appid and appsecret keys: 
https://gist.github.com/729bc24a493c23af546f.git

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_SCLFlicButton", referenced from:
      testflic.ViewController.flicManagerDidRestoreState (testflic.ViewController)(ObjectiveC.SCLFlicManager) -> () in ViewController.o
      type metadata accessor for ObjectiveC.SCLFlicButton in ViewController.o
  "_OBJC_CLASS_$_SCLFlicManager", referenced from:
      type metadata accessor for ObjectiveC.SCLFlicManager in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by AntonMeier** [comment]
Hi, Swift compatibility should not be an issue, I am currently running a Swift app just fine with it. The problem that you are seeing I believe occurs because you are trying to run the framework in the simulator, am I correct? Currently the framework is not built for both simulator and device. We have been looking at it and might add support for it in the future, but for now it is not the highest priority. Hope that answers your question. Apologize for the inconvenience!

**Comment by galileomd** [comment]
ah.. trying on actual device… now getting THIS error:
dyld: Library not loaded: @rpath/fliclib.framework/fliclib
  Referenced from: /private/var/mobile/Containers/Bundle/Application/832470B6-F107-40AB-A1C9-DDAB16E5736A/testflic.app/testflic
  Reason: image not found

any chance you could post a working swift demo?

**Comment by AntonMeier** [comment]
Sounds like you might have forgot to do Step 4 under "Set up xcode" in the iOS Tutorial Part 1, but I could be wrong. I'll take a look at it tomorrow and will try to upload a working swift demo within a few days or so.

**Comment by galileomd** [comment]
i made sure to include the bridging header in the build settings... will look forward to your demo. thanks!

**Comment by AntonMeier** [comment]
Posted a demo project earlier today that you can take a look at. "ios-boilerplate-swift".
