### ISSUE TITLE
Flic 2 support

### ISSUE THREAD

**Issue by arlomedia** [50ButtonsEach/fliclib-ios#37]
Do we need a framework update to support the Flic 2? It hasn't been updated since long before the Flic 2 launch, but a user with a Flic 2 says his button shows as "Not Compatible" in the picker.

![flic_2](https://user-images.githubusercontent.com/1878401/70930143-5a3cda80-1fe9-11ea-83f5-26b8ad9de888.png)

**Comment by AntonMeier** [comment]
We are very close to releasing a framework with Flic 2 support. We are talking a few days :)

It will be on a separate repository though and a different framework all together. It will also be a different approach as you will no longer need to use the Flic app in order to pair and use Flic 2 buttons with third party apps.

**Comment by arlomedia** [comment]
Thanks. Will the new framework also support the original Flic buttons?

**Comment by Emill** [comment]
No, but you can use both in parallel.

**Comment by AntonMeier** [comment]
You may have a look at [flic2lib-ios](https://github.com/50ButtonsEach/flic2lib-ios)

**Comment by arlomedia** [comment]
Cool, thanks for following up.
